---
module:
  imports:
    - path: github.com/krisk/Fuse
      mounts:
        - source: ./
          target: assets/fuse.js

    - path: github.com/danisztls/lite-search
      mounts:
        - source: ./
          target: assets/lite-search
