---
module:
  imports:
    - path: github.com/krisk/Fuse
      mounts:
        - source: dist/fuse.esm.js
          target: assets/fuse.js/dist/fuse.esm.js

    - path: github.com/danisztls/lite-search
      mounts:
        - source: index.js
          target: assets/lite-search/index.js
