---
baseURL: ""
languageCode: 'en-us'
title: 'Lite Search Demo'

module:
  imports:
    - path: github.com/krisk/Fuse
      mounts:
        - source: dist
          target: assets/fuse

    - path: github.com/danisztls/lite-search
      mounts:
        - source: search.js
          target: assets/search.js

outputs:
  home: ["html", "json"]
