---
module:
  imports:
    - path: github.com/krisk/Fuse
      mounts:
        - source: ./
          target: assets/fuse.js

  mounts:
    - source: assets
      target: assets

    - source: ../
      target: assets/lite-search
